---
abstract: 'Official MongoDB Driver for Perl'
author:
  - 'David Golden <david.golden@mongodb.org>'
  - 'Mike Friedman <friedo@mongodb.com>'
  - 'Kristina Chodorow <kristina@mongodb.org>'
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  Data::Dumper: '0'
  DateTime::Tiny: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  FileHandle: '0'
  JSON: '0'
  Test::Deep: '0.111'
  Test::Fatal: '0'
  Test::More: '0.96'
  Test::Warn: '0'
  bigint: '0'
  lib: '0'
  threads: '0'
  utf8: '0'
configure_requires:
  Config::AutoConf: '0.22'
  ExtUtils::MakeMaker: '0'
  Path::Tiny: '0.052'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.027, CPAN::Meta::Converter version 2.142060'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MongoDB
no_index:
  directory:
    - devel
    - inc
    - t
    - xt
provides:
  MongoDB:
    file: lib/MongoDB.pm
    version: v0.707.2.0
  MongoDB::BSON:
    file: lib/MongoDB/BSON.pm
    version: v0.707.2.0
  MongoDB::BSON::Binary:
    file: lib/MongoDB/BSON/Binary.pm
    version: v0.707.2.0
  MongoDB::BSON::Regexp:
    file: lib/MongoDB/BSON/Regexp.pm
    version: v0.707.2.0
  MongoDB::BulkWrite:
    file: lib/MongoDB/BulkWrite.pm
    version: v0.707.2.0
  MongoDB::BulkWriteView:
    file: lib/MongoDB/BulkWriteView.pm
    version: v0.707.2.0
  MongoDB::Code:
    file: lib/MongoDB/Code.pm
    version: v0.707.2.0
  MongoDB::Collection:
    file: lib/MongoDB/Collection.pm
    version: v0.707.2.0
  MongoDB::CommandResult:
    file: lib/MongoDB/CommandResult.pm
    version: v0.707.2.0
  MongoDB::Connection:
    file: lib/MongoDB/Connection.pm
    version: v0.707.2.0
  MongoDB::ConnectionError:
    file: lib/MongoDB/Error.pm
    version: v0.707.2.0
  MongoDB::Cursor:
    file: lib/MongoDB/Cursor.pm
    version: v0.707.2.0
  MongoDB::DBRef:
    file: lib/MongoDB/DBRef.pm
    version: v0.707.2.0
  MongoDB::Database:
    file: lib/MongoDB/Database.pm
    version: v0.707.2.0
  MongoDB::DatabaseError:
    file: lib/MongoDB/Error.pm
    version: v0.707.2.0
  MongoDB::DocumentSizeError:
    file: lib/MongoDB/Error.pm
    version: v0.707.2.0
  MongoDB::Error:
    file: lib/MongoDB/Error.pm
    version: v0.707.2.0
  MongoDB::GridFS:
    file: lib/MongoDB/GridFS.pm
    version: v0.707.2.0
  MongoDB::GridFS::File:
    file: lib/MongoDB/GridFS/File.pm
    version: v0.707.2.0
  MongoDB::MongoClient:
    file: lib/MongoDB/MongoClient.pm
    version: v0.707.2.0
  MongoDB::OID:
    file: lib/MongoDB/OID.pm
    version: v0.707.2.0
  MongoDB::Timestamp:
    file: lib/MongoDB/Timestamp.pm
    version: v0.707.2.0
  MongoDB::WriteConcernError:
    file: lib/MongoDB/Error.pm
    version: v0.707.2.0
  MongoDB::WriteError:
    file: lib/MongoDB/Error.pm
    version: v0.707.2.0
  MongoDB::WriteResult:
    file: lib/MongoDB/WriteResult.pm
    version: v0.707.2.0
requires:
  Authen::SCRAM::Client: '0.003'
  Carp: '0'
  Class::MOP::Class: '0'
  DateTime: '0.78'
  Digest::MD5: '0'
  Encode: '0'
  Exporter: '5.57'
  IO::File: '0'
  MIME::Base64: '0'
  Moose: '0'
  Moose::Meta::Class: '0'
  Moose::Role: '0'
  Moose::Util::TypeConstraints: '0'
  Safe::Isa: '0'
  Scalar::Util: '0'
  Syntax::Keyword::Junction: '0'
  Throwable: '0'
  Tie::IxHash: '0'
  Time::HiRes: '0'
  Try::Tiny: '0'
  XSLoader: '0'
  boolean: '0'
  constant: '0'
  if: '0'
  namespace::clean: '0'
  overload: '0'
  perl: '5.008'
  strict: '0'
  version: '0'
  warnings: '0'
resources:
  bugtracker: https://jira.mongodb.org/browse/PERL
  homepage: https://github.com/mongodb/mongo-perl-driver
  repository: https://github.com/mongodb/mongo-perl-driver.git
version: v0.707.2.0
