---
abstract: 'Super Awesome Perl Library'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires:
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MongoDB
requires:
  perl: v5.10.0
resources:
  bugtracker: https://github.com/alnewkirk/MongoDB/issues
  homepage: https://github.com/alnewkirk/MongoDB
  repository: https://github.com/alnewkirk/MongoDB.git
version: 0.01
x_authority: cpan:AWNCORP
